# application config
server:
  port: ${SERVER_PORT:8112}

# spring config
spring:
  application:
    name: ${APPLICATION_NAME:80087df70c115c95c44408cb62fba63cf778c09c37c5c59ecd9788767a856da5}

  # mongo db config
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/PaymentQueryService}
      database: ${MONGODB_DATABASE:PaymentQueryService}

  # rabbitmq config
  rabbitmq:
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    ignoreDeclarationException: ${RABBITMQ_IGNORE_DECLARATION_EXCEPTION:true}
    concurrentConsumers: ${RABBITMQ_CONCURRENT_CONSUMERS:3}
    maxConcurrentConsumers: ${RABBITMQ_MAX_CONCURRENT_CONSUMERS:10}
    receiveTimeout: ${RABBITMQ_RECEIVE_TIMEOUT:100000}